networks:
  default: development
  development:
    gas_limit: max
    gas_buffer: 1
    gas_price: 0
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings: null
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0
compiler:
  solc:
    version: 0.6.11
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"
